#Create a list of all the items and witty responses if I feel like it for each item on each puzzle.

item = [
	["key",
	"Ah. Of course... It's the morning... anyways...",
	"I think jangling keys only works with babies.",
	"I'd rather not lose this.",
	"I'm going to need that for later..",
	"No, that's not it.",
	"I need this.",
	"To strangers? No...",
	"Keep this away.",
	"It's cold enough to shatter this.",
	"Stop trying to use this on everything.",
	"Not my house.",
	"Doesn't fit in any of their ears.",
	"I do have something sharper.",
	"I can't unlock his armor with that.",
	"A pond is a safe place to throw a key.",
	"Log.",
	"",
	"Just barely too small to make it across.",
	"Too sharp to be swinging around."],
	
	["axe",
	"",
	"I don't think I could get close enough before I get mauled to death.",
	"I think I like to keep my kills mostly intact.",
	"I look like a murderer with a bloody axe.",
	"That seems right.",
	"I need the bridge repaired, brain.",
	"They're in bigger numbers than me.",
	"They step back. I better put this away.",
	"How?",
	"I have something less messy to use.",
	"He's got plenty of those.",
	"I don't think I want to do that.",
	"Plant, not tree.",
	"'A flesh wound!'",
	"I think the mother pond would be upset if I axed her little pond.",
	"Log.",
	"",
	"Too sharp to walk on.",
	"Doesn't do much good."],
	
	["bow",
	"",
	"Trusty bow. And off you go!",
	"Goodbye beautiful creature. -sniff-",
	"Never!",
	"It's not cutting very well..",
	"It's not large enough.",
	"Not sure I want human tonight.",
	"They don't seem hostile.",
	"Yes, use bow to get me some warm clothes.",
	"Nothing left to kill.",
	"Nothing to hunt here.",
	"Hunt of the Children.",
	"Too sharp, could hurt myself using this.",
	"Deflected.",
	"Good idea, I'll fill my bow with water for later.",
	"Log.",
	"",
	"Got a bird!",
	"Keeps getting stuck."],
	
	["knife",
	"",
	"To take down a bear? Maybe if I was a monster.",
	"I'd be skewered if I had to get that close.",
	"This is a stick-up! Kidding.",
	"Don't want to dull this thing.",
	"Repair. Not destroy.",
	"I could get one, but then they'd get me.",
	"A quick end. If I wanted to.",
	"Use knife to make me some warm clothes.",
	"There we are.",
	"For what?",
	"They've got proper tanning knives.",
	"Just the right dullness.",
	"Not even a scratch.",
	"Die water die!",
	"Log.",
	"",
	"Not long enough.",
	"Only cut one plant."],
	
	["rawmeat",
	"",
	"",
	"I sure wouldn't eat this, why would it?",
	"Smelly. May as well try.",
	"I can coax some bears to do it for me..",
	"I'll use this to catch a pterodactyl and fly it across!",
	"I could smell them out...",
	"It would smell this cave up. No thanks.",
	"Preserved now, forever.",
	"To lure the leopard back? No thanks.",
	"I wouldn't eat it, he won't.",
	"Must I show everything this?",
	"Gross. Instant spoiled in this weather.",
	"Ignored.",
	"The sitting pond gets up and moves away from me.",
	"Log.",
	"",
	"The cliff smells it and moves further away. Crap.",
	"The bushes move back, but do not part ways."],
	
	["backpack",
	"",
	"",
	"Yes, but I need to detach the horn first.",
	"There's plenty of stuff _inside_ it brain.",
	"It's worse than my bow for cutting.",
	"Look in it. In. The backpack.",
	"Do I have anything in here?",
	"I'm afraid to look. You choose, brain.",
	"Do I have some warm socks in there? Jeeze.",
	"I can't take the entire thing with me.",
	"He doesn't fit.",
	"The children would probably scream.",
	"I can't fit the jungle in my bag.",
	"Too heavy to carry after putting him inside.",
	"Too watery to hold with a bag.",
	"Log in there.",
	"",
	"The ravine doesn't fit in the bag.",
	"Lots of thorns. Ouch."],
	
	["log",
	"",
	"It's too light to do any damage.",
	"Still too light to do damage.",
	"He yawns.",
	"",
	"Not going to work this time, much too wide.",
	"They don't even look over at me pulling one out.",
	"They look surprised at me hiding this in my backpack.",
	"It looks bloated.",
	"Too big to roast.",
	"I got some of these.",
	"They have no use for it.",
	"I can use a log to sharpen a log to use that log to..",
	"He takes the battering ram full force, unphased.",
	"Okay, now what.",
	"Yay.",
	"",
	"This will do nicely.",
	"Doesn't do much flattening."],
	
	["hide",
	"",
	"",
	"Maybe if I wear this.. wait what?",
	"He's slightly interested, but not today.",
	"",
	"Huh?",
	"Become one with nature. I am the Yak. No response.",
	"I've already got a jacket on.",
	"I can't exactly wear that yet.",
	"",
	"I can't process that here.",
	"If they need more, sure.",
	"Hide from the bugs? Har har... okay.",
	"His looks more stylish.",
	"Gross, now it smells like wet dog.",
	"Log.",
	"",
	"",
	"Do what who."],
	
	["ropeplant",
	"",
	"",
	"I'd rather not try to strangle this beast.",
	"I could use this myself, no sense trading it.",
	"",
	"Don't have enough to weave me a new bridge.",
	"Bracelets anyone?",
	"They don't want bracelets.",
	"BRACELETS AREN'T WARM.",
	"Dead things don't need bracelets.",
	"He looks too manly for a bracelet.",
	"Hello Children, would you like a bracelet?",
	"",
	"He happily takes a bracelet, but doesn't move.",
	"Not interested.",
	"Log.",
	"",
	"",
	"They love the bracelets."],
	
	["plank",
	"",
	"",
	"Even less harmful than a log.",
	"He looks at me, 'really?'",
	"",
	"Right choice that is.",
	"Don't have enough to box them in.",
	"And do what?",
	"I'd need a lot of these for a lot of fires.",
	"I could make a fire.. But why.",
	"",
	"What for?",
	"Smokey says this is a bad idea.",
	"Cowers, but doesn't move.",
	"Fish aren't biting.",
	"Log.",
	"",
	"",
	""],
	
	["fishingpole",
	"",
	"",
	"Best I could do is catch some hair off it.",
	"Not even considered.",
	"",
	"I can catch the other cliff and pull it to me!",
	"Catch a finger?",
	"Nothing to catch here.",
	"Ice fishing!",
	"Fishing for corpses!",
	"I can't unprocess that.",
	"Fishing for children.",
	"",
	"I can't get a good hook on him.",
	"I guess this could work.",
	"Log.",
	"",
	"",
	""],
	
	["strangeorb",
	"",
	"",
	"I don't even want to touch this.",
	"He looks really frightened. What is this thing?",
	"",
	"That stays in the bag.",
	"They crowd around me when I take it out. But that's it.",
	"They instantly kneel down at the sight of it.",
	"",
	"",
	"Stay in the bag.",
	"",
	"",
	"He turns the other way, but doesn't move.",
	"All the fish scatter.",
	"Log.",
	"",
	"",
	""],
	
	["ritualbook",
	"",
	"",
	"",
	"",
	"",
	"",
	"They crowd around and one gestures if they can have it.",
	"Forgot I gave it away.",
	"It starts to shiver. Creepy.",
	"Dear Diary, Today I watched animals fight to the death.",
	"He has no idea what it is.",
	"I'd rather not creep them out.",
	"Hear me Peacocks of the Jungle! Assist me! No response.",
	"'Is that your diary? Hah!'",
	"Dear Diary, Today I visited the ponds.",
	"Log.",
	"",
	"",
	""],
	
	["machete",
	"",
	"",
	"Errr, I think I have something safer.",
	"I think I scared him.",
	"",
	"Repair, not break more.",
	"I'm no maniac.",
	"Still not a maniac.",
	"No? What?",
	"Not very good at disassembling corpses.",
	"Don't scare the poor guy.",
	"Screams of terror would follow.",
	"I don't want to damage them too much.",
	"I scratched him!",
	"Stab stab.",
	"Log.",
	"",
	"",
	"Works wonders on the hair."],
	
	["jacket",
	"",
	"",
	"I'll put it on the unicorn and make it sweat to death!",
	"Not interested.",
	"",
	"That only works for puddles.",
	"It is getting colder. I'll put this on.",
	"Already put it on. It's pretty cold here.",
	"Beautifully made.",
	"",
	"He's got one.",
	"",
	"",
	"He still recognizes me.",
	"Warm. Smells.",
	"Log.",
	"",
	"",
	""],
	
	["herring",
	"",
	"",
	"I don't think they like fish.",
	"He doesn't look interested.",
	"",
	"Fish bridge! Wait, dumb brain stop it.",
	"Unlike the Black Knight, they don't seem to care.",
	"'A HERRRINGGG!' can be heard off in the distance.",
	"Refrigerated.",
	"Too dead to care.",
	"Not interested.",
	"They hate herring.",
	"Chop with a herring!",
	"'A HERRINGGG!'",
	"",
	"Log.",
	"",
	"",
	""],
	
	["unicornhorn",
	"",
	"",
	"",
	"I guess he's not so looney.",
	"",
	"",
	"They don't even care.",
	"No response.",
	"Nayyyyy~",
	"And do what with it.",
	"He thinks I'm trying to scam him.",
	"Their mother calls me creepy. :c",
	"",
	"",
	"",
	"Log.",
	"",
	"",
	""]
	]